---

- name: Get Terraform scripts
  git:
    repo: '{{ terraform_project_repo }}'
    dest: '{{ terraform_dir }}'
    version: '{{ terraform_project_version }}'

- name: Generate Terraform vars
  template:
    src: '{{ template_tfvars }}'
    dest: '{{ terraform_dir }}/layers/{{ terraform_layer }}/terraform.tfvars.json'
    mode: 0644

- name: Terraform
  terraform:
    force_init: true
    project_path: '{{ terraform_dir }}/layers/{{ terraform_layer }}'
    state: '{{ state }}'
    binary_path: "{{ terraform_bin | d(omit) }}"
    workspace: "{{ terraform_workspace }}"
    state_file: "{{ terraform_state_file }}"
    init_reconfigure: true
  environment: '{{ terraform_env_vars | combine(terraform_extra_env_vars) }}'